services:
  - type: web
    name: turo-fleet-manager-api
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: turo-fleet-db
          property: connectionString

databases:
  - name: turo-fleet-db
    databaseName: turo_fleet
    user: turo_fleet_user
    region: oregon
    plan: free
